name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Lint and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
      - run: |
          npm ci
          npm run lint
          npm run verify-solution

  automerge:
    name: Merge dependabot's PRs
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
